# Generated by Django 4.1 on 2023-05-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesmodel',
            name='pname',
        ),
        migrations.AddField(
            model_name='livesmodel',
            name='empid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emp.worksmodel'),
        ),
        migrations.AddField(
            model_name='worksmodel',
            name='empid',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='pname',
            field=models.CharField(max_length=100),
        ),
    ]
