# Generated by Django 4.1 on 2023-05-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_remove_livesmodel_pname_livesmodel_empid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesmodel',
            name='empid',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='worksmodel',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.livesmodel'),
        ),
    ]
