# Generated by Django 4.1 on 2023-05-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_livesmodel_empid_alter_worksmodel_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksmodel',
            name='empid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emp.livesmodel'),
        ),
    ]
