# Generated by Django 2.2.28 on 2023-05-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('addr', models.TextField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
