# Generated by Django 2.2.28 on 2023-05-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230505_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebookmodel',
            name='bname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.BookModel'),
        ),
    ]
